version: "2.0"

services:
  ssl-proxy:
    env_file: .env
    extends:
      file: ./services/ssl-proxy/docker-compose.yml
      service: ssl-proxy
    depends_on:
      - php-apache
#    ports: # uncomment to bind for used OS (http/s request flow: ssl-proxy -> varnish -> nginx)
#      - "${IP_ADDRESS}:80:80" # linux
#      - "${IP_ADDRESS}:443:443" # linux
#        - "80:80" # macos
#        - "443:443" # macos

#  varnish:
#    env_file: .env
#    extends:
#      file: ./services/varnish/docker-compose.yml
#      service: varnish
#    depends_on:
#      - nginx
#    ports: # uncomment to bind for used OS (for varnish-nginx to avoid ssl-proxy, no https)
#      - "${IP_ADDRESS}:80:80" # linux
#      - "80:80" # macos

  php-apache:
    env_file: .env
    extends:
      file: ./services/php7-apache/docker-compose.yml
      service: php-apache
    volumes:
#      - ${LOCALHOST_PROJECT_PATH}:${CONTAINER_PROJECT_PATH}:delegated # mount project sources from localhost folder
      - ${LOCALHOST_PROJECT_PATH}/magento:${CONTAINER_PROJECT_PATH}:delegated
      - ${LOCALHOST_PROJECT_PATH}/magento/.modman:${CONTAINER_PROJECT_PATH}/.modman:delegated
      - ${LOCALHOST_PROJECT_PATH}/repo:/var/www/repo:delegated
#     section below is for those who really knows what to do :)
#      - ./diff-files/ssh:/var/www/.ssh:delegated
#     section below for macos, mount "magento" volume, if you want to keep /var/www/src contents after container deletion without mounting folder from localhost
#      - magento:/var/www/src
    depends_on:
      - mysql
      - redis
      - mailhog
#    ports:
#      - "${IP_ADDRESS}:80:80"

  mysql:
    env_file: .env
#    command: --max_allowed_packet=32505856
    extends:
      file: ./services/mysql/docker-compose.yml
      service: mysql
    ports: # uncomment to bind for used OS
      - "${IP_ADDRESS}:3306:3306" # linux
#      - "3306:3306" # macos

# uncomment this service, and you will be able to connect to mysql
# with IP_ADDRESS:8080 with mysql_host=mysql, user=root, password=root
#  phpmyadmin:
#    env_file: .env
#    extends:
#      file: ./services/phpmyadmin/docker-compose.yml
#      service: phpmyadmin
#    depends_on:
#      - mysql
#    ports: # uncomment to bind for used OS
#      - "${IP_ADDRESS}:8080:80" # linux
#      - "8080:80" # macos

  redis:
    env_file: .env
    extends:
      file: ./services/redis/docker-compose.yml
      service: redis

  mailhog:
    env_file: .env
    extends:
      file: ./services/mailhog/docker-compose.yml
      service: mailhog
    ports: # webui, uncomment to bind for used OS
      - "${IP_ADDRESS}:8025:8025" # linux
#      - "8025:8025" # macos

# uncomment section below to use volumes feature
#volumes:
#  magento:
