version: "2.0"

services:
  mailhog:
    image: mailhog/mailhog
    env_file:
      - .env
    logging:
      driver: 'none' # disable saving logs
    command: ["-storage=maildir", "-maildir-path=/maildir"]
    volumes:
      - ./../../volumes/mailhog:/maildir:delegated
