version: "2.0"

services:
  rabbitmq:
    image: rabbitmq:3.9-management
    env_file:
      - .env
    volumes:
      - ./../../volumes/rabbitmq:/var/lib/rabbitmq:cached
    environment:
      - RABBITMQ_DEFAULT_USER=${COMPOSE_PROJECT_NAME}
      - RABBITMQ_DEFAULT_PASS=${COMPOSE_PROJECT_NAME}
