version: "2.0"

services:
  mysql:
#    platform: linux/x86_64 # uncomment if need arm support (apple silicon CPU), comment if not :D
    build:
      context: ./
      dockerfile: 8.0/Dockerfile
    env_file:
      - .env
    volumes:
      - ./../../volumes/mysql:/var/lib/mysql:cached
