version: "2.0"

services:
  ssl-proxy:
    build: ./
    env_file:
      - .env
    volumes:
      - ./conf/localhost.template:/etc/nginx/docker/localhost.template:cached
      - ./certificates/:/etc/ssl/certs/
